### ISSUE TITLE
No request.js dependency

### ISSUE THREAD

**Issue by stevenvachon** [eventEmitter/request-rate-limiter#1]
It'd be better if we could depend on request directly and use this lib with it. Additionally, this would open the possibility of using other libs that are similar to request.

**Comment by colinodell** [comment]
+1

**Comment by linaGirl** [comment]
@stevenvachon @colinodell any idea how an interface for this should look like?

**Comment by stevenvachon** [comment]
could be done similar to what i did with [limited-request-queue](https://github.com/stevenvachon/limited-request-queue)

**Comment by linaGirl** [comment]
@stevenvachon thanks! i just implemented and published a simple interface that allows you to use your own request implementation.
