### ISSUE TITLE
How do you specify a burst rate?

### ISSUE THREAD

**Issue by graemian** [eventEmitter/request-rate-limiter#6]
The headline for the project says

> Call HTTP APIs that have rate limits and allow request **bursts**

but I can't quite figure out how to specify a burst rate. I'm trying to implement this policy:

> Calls to the Market Data APIs are rate limited to 1 call per 10 seconds. API call rate limits allow bursts of up to five consecutive calls. Exceeding the limit causes HTTP error code 429 to be returned.

This is the closest I can get:

    new RateLimiter({

        rate: 5,
        interval: 10,
        backoffTime: 10

    })

Is that correct, or am I missing something?

**Comment by linaGirl** [comment]
You are allowed to send 1 call every 10 seconds or 5 calls every 50 seconds. This means probably that they are using a leaky bucket with that configuration. The correct parameters are probably those:

- rate: 5
- interval: 50
- backoffTime: 10

This should allow you to send 5 requests as a burst and after that bout every 10 seconds another one.
