### ISSUE TITLE
Document Bottleneck as an alternative

### ISSUE THREAD

**Issue by rjruizes** [eventEmitter/request-rate-limiter#8]
I found request-rate-limiter because its name describes the problem I'm trying to solve. When searching for other packages that do the same thing, I found [Bottleneck](https://github.com/SGrondin/bottleneck), a more robust solution. It would be nice for the documentation to mention Bottleneck as an alternative. For example, Bottleneck supports rate limit jobs across multiple Node.js instances, which is a very helpful feature.

**Comment by linaGirl** [comment]
Hi @rjruizes thanks for the input. Feel free to create a pull request for this.
