### ISSUE TITLE
Handling requests that don't return

### ISSUE THREAD

**Issue by graemian** [eventEmitter/request-rate-limiter#9]
I think my bucket is filling up with HTTP requests that don't return, possibly due to network error. Eventually I get the error that the request can't be scheduled because the max time would be exceeded.

Is there a way to know if this is the case? Bucket queue length doesn't increase, but waitTime climbs over time.

I see request has support for timeouts (https://github.com/request/request#timeouts), but I'm not sure if I trust it. Maybe I need to wrap request such that the rate limiter callback is invoked if request doesn't return within a certain time.

Any suggestions would be appreciated.

**Comment by graemian** [comment]
It would be even better if the rate limiter could automatically handle this :-)

**Comment by linaGirl** [comment]
Thanks for reporting the issue. I will have a look into it on Sunday.

**Comment by linaGirl** [comment]
@graemian you can either [pass functions](https://github.com/eventEmitter/request-rate-limiter#api-using-your-own-request-implementation) to the `request` method and implement the actual request yourself or set the parameter `{timeout: x}` on the config you pass to the `request` method. Both should work.

**Comment by graemian** [comment]
Thanks. So you agree that if you don't pass the timeout param, the bucket could fill up if requests don't ever return?

I've wrapped my calls with counters to detect if this is what is happening. I read the documentation on request's timeout param. I'm not sure I trust it to always time out - it seems to rely on low-level OS stuff. 

In that case, I see 2 solutions: construct a pass function that wraps request and has an explicit timeout using setTimeout, or build this same thing into request-rate-limiter directly. 

What are your thoughts on this? Would you accept a pull request as above, or do you prefer to rely on request's timeout param? I suppose I could run my app for a while using that and see if it still breaks...

**Comment by linaGirl** [comment]
You might be right, the timeout might be a bit risky to depend on (I never tried it though). Your proposed solution might help, but it might also lead to more problems. The sockets that are hanging will hog resources, that are not being freed while you are allocating new resources for the other requests.

I will however gladly accept a pull request, as long the functionality is configurable using an option for the constructor.
